R328328:
  - camera_id: 'cam_1'
    rtsp: rtsp://127.0.0.1:8554/test
  - camera_id: 'cam_2'
    rtsp: rtsp://127.0.0.1:8553/test
R329329:
  - camera_id: 'cam_3'
    rtsp: rtsp://127.0.0.1:8552/test
R327327:
  - camera_id: 'cam_4'
    rtsp: rtsp://127.0.0.1:8554/test
