R328328:
  - camera_id: video/test.flv
    channel_name: test
  - camera_id: rtsp://127.0.0.1:8554/test
    channel_name: movie
R329329:
  - camera_id: rtsp://127.0.0.1:8554/test
    channel_name: result
