R328328:
  - camera_id: 1
    rtsp: rtsp://127.0.0.1:8554/test
    channel_name: test
  - camera_id: 2
    rtsp: rtsp://127.0.0.1:8554/test
    channel_name: movie
R329329:
  - camera_id: 3
    rtsp: rtsp://127.0.0.1:8554/test
    channel_name: result
