name: ci

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: openv2x/hippocampus:latest
          build-args: |
            GIT_BRANCH=${{ github.ref_name }}
            REPO_URL=https://github.com/open-v2x/hippocampus
            GIT_COMMIT=${{ github.sha }}
  ssh:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: apply to cicd environment & sync image to ACR
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LAB_HOST }}
          username: ${{ secrets.LAB_USERNAME }}
          password: ${{ secrets.LAB_PASSWORD }}
          port: ${{ secrets.LAB_PORT }}
          script: |
            set -e

            containerName="livego" 

            if [[ -n $(docker ps -q -f "name=^${containerName}$") ]];then
              echo "container already exist"
            else
              docker run -p 1935:1935 -p 7001:7001 -p 7002:7002 -p 8090:8090 -d --name=livego gwuhaolin/livego
            fi

            containerName1="gst-rtsp-launch"

            if [[ -n $(docker ps -q -f "name=^${containerName1}$") ]];then
              echo "container already exist"
            else
              docker run -v ~/Videos/test.mp4:/test.mp4 --rm -it -p 8554:8554 --name=gst-rtsp-launch steabert/gst-rtsp-launch "filesrc location=/test.mp4 ! decodebin ! x264enc ! rtph264pay name=pay0 pt=96"
            fi

            docker stop hippocampus-328 hippocampus-329|| true
            docker rm hippocampus-328 hippocampus-329 || true
            docker rmi openv2x/hippocampus:latest || true
            docker pull openv2x/hippocampus:latest
            nvidia-docker run -d --env "RSU=R328328" --name=hippocampus-328 --gpus all --net=host -v ~/Videos/test.mp4:/home/hippocampus/video/test.mp4 -v ~/Videos/test1.mp4:/home/hippocampus/video/test1.mp4 openv2x/hippocampus:latest
            nvidia-docker run -d --env "RSU=R329329" --name=hippocampus-329 --gpus all --net=host -v ~/Videos/test.mp4:/home/hippocampus/video/test.mp4 -v ~/Videos/test1.mp4:/home/hippocampus/video/test1.mp4 openv2x/hippocampus:latest
            docker tag openv2x/hippocampus:latest registry.cn-shanghai.aliyuncs.com/openv2x/hippocampus:latest
            docker push registry.cn-shanghai.aliyuncs.com/openv2x/hippocampus:latest
       
  acr:
      needs: docker
      runs-on: ubuntu-latest
      steps:
        - name: sync image to ACR
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.AIO_MASTER_HOST }}
            username: ${{ secrets.AIO_MASTER_USERNAME }}
            key: ${{ secrets.AIO_MASTER_KEY }}
            port: ${{ secrets.AIO_MASTER_PORT }}
            script: |
              docker pull openv2x/hippocampus:latest
              docker tag openv2x/hippocampus:latest registry.cn-shanghai.aliyuncs.com/openv2x/cerebrum:latest
              docker push registry.cn-shanghai.aliyuncs.com/openv2x/hippocampus:latest